// Regenerates docs/whatsapp-templates.md from WHATSAPP_TEMPLATES, so the
// text submitted to Meta always matches what the app sends.
//   node --experimental-strip-types scripts/generate-template-doc.ts
import { writeFileSync } from "node:fs";
import { WHATSAPP_TEMPLATES, fillTemplate } from "../src/server/delivery/messages.ts";

const sections = Object.values(WHATSAPP_TEMPLATES).map((t) => [
  `## \`${t.name}\``,
  "",
  "Body (paste exactly, including line breaks and emoji):",
  "",
  "```",
  t.body,
  "```",
  "",
  `Sample values for Meta's review: ${t.example.map((v, i) => `{{${i + 1}}} = \`${v}\``).join(", ")}`,
  "",
  "Preview:",
  "",
  "> " + fillTemplate(t.body, t.example).split("\n").join("\n> "),
  "",
].join("\n"));

writeFileSync(
  new URL("../docs/whatsapp-templates.md", import.meta.url),
  [
    "# WhatsApp message templates",
    "",
    "<!-- Generated by scripts/generate-template-doc.ts from src/server/delivery/messages.ts. Edit there, then regenerate. -->",
    "",
    "WhatsApp only allows free-form messages within 24 hours of the customer's last message. Delivery updates often arrive later, so each one needs a pre-approved template. Create each template below in **WhatsApp Manager → Message templates → Create template** with:",
    "",
    "- **Category:** Utility",
    "- **Name:** exactly as shown (lowercase with underscores)",
    "- **Language:** English. Set the `WHATSAPP_TEMPLATE_LANGUAGE` variable to the same language code Meta shows (`en` or `en_US`).",
    "- **Body:** exactly as shown. Add the sample values when Meta asks for them.",
    "",
    "Inside the 24-hour window the app sends the same text as a normal message, so customers see the same wording either way.",
    "",
    ...sections,
  ].join("\n"),
);
console.log("Wrote docs/whatsapp-templates.md");
